# Generated by Django 2.2.4 on 2019-08-24 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='iletisim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Adı', models.CharField(max_length=50)),
                ('soyAdı', models.CharField(max_length=50)),
                ('giris_zamani', models.DateTimeField(default=django.utils.timezone.now)),
                ('giris', models.TextField(null=True)),
            ],
        ),
    ]
