# Generated by Django 2.1.1 on 2019-08-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iletisim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iletisim',
            name='email',
            field=models.EmailField(default='aa@aa.com', max_length=254),
        ),
    ]
