# Generated by Django 2.1.1 on 2019-08-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iletisim', '0002_iletisim_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iletisim',
            name='email',
            field=models.EmailField(blank=True, default='aa@aa.com', max_length=254),
        ),
    ]
