# Generated by Django 2.1.1 on 2019-08-25 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iletisim', '0003_auto_20190825_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='iletisim',
            name='girisIP',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
