# Generated by Django 2.1.1 on 2019-08-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Iletisim', '0004_iletisim_girisip'),
    ]

    operations = [
        migrations.AddField(
            model_name='iletisim',
            name='Onay',
            field=models.BooleanField(default=False),
        ),
    ]
